### ISSUE TITLE
use ts.CompilerOptions

### ISSUE THREAD

**Issue by basarat** [TypeStrong/tsconfig#1]
and not our own custom `CompilerOptions` interface.

**Comment by Zoltu** [comment]
Reference: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L1646-L1682

In the meantime, perhaps copy and paste would at least be better than the current situation where most options can't be set?

**Comment by blakeembrey** [comment]
Closing this now for now, we're still not using the TypeScript compiler options interface but I don't think it's necessary. The type information is accurate according to what can exist in `tsconfig.json`, if you want those types you could type cast using TypeScript. Correct me if this seems unreasonable though :smile:
