### ISSUE TITLE
Does `tsconfig` support a fully blank tsconfig.json file?

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/tsconfig#10]
The TypeScript wiki says that it's valid for tsconfig.json to be completely blank.

Sorry I haven't tested this - I just noticed this bullet point and wanted to document it somewhere.  I suspect that `tsconfig` should just use `{}` instead of null or something...

**Comment by blakeembrey** [comment]
Is that the wrong issue linked?

**Comment by nycdotnet** [comment]
Sorry - paste fail.

**Comment by blakeembrey** [comment]
By the way, it is supported and treated as if it's an empty object. From there, `files` expansion kicks in anyway and you end up with `files` and `exclude`, as well as an empty `compilerOptions` object.
