### ISSUE TITLE
Exclude a directory but include a sub file

### ISSUE THREAD

**Issue by basarat** [TypeStrong/tsconfig#11]
Migrated issue report by @sickboy : https://github.com/TypeStrong/atom-typescript/issues/651#issuecomment-146892270: :rose: 

----

@blakeembrey Excluding works again thanks.
BUT I can not override excludes anymore.

~~~
        "!./cdn/aurelia/jspm_packages/npm/rx@*/ts/**/*.ts",
        "./cdn/aurelia/jspm_packages/npm/rx@*/ts/rx.all.es6.d.ts"
~~~
should still give me "rx.all.es6.d.ts" but it doesn't. The order doesn't seem to matter.
Would be great if it could do first match perhaps.

so then it should be configured as:

~~~
        "./cdn/aurelia/jspm_packages/npm/rx@*/ts/rx.all.es6.d.ts"
        "!./cdn/aurelia/jspm_packages/npm/rx@*/ts/**/*.ts",
~~~

and then because it hits the first one, it should no longer look at the next

**Comment by blakeembrey** [comment]
Thanks, working on it - I'm going to release `2.0` of the API and switch to `globby`. Almost done now, give me an hour :+1: It'll also fix the `compilerOptions` issue, which is the main reason to break backward compat.

**Comment by blakeembrey** [comment]
Released with `v2.0.0` :+1:

**Comment by nycdotnet** [comment]
Way to go, man!

**Comment by basarat** [comment]
:rose: :heart_eyes:

**Comment by sickboy** [comment]
Thanks, this fixed the glob issue.
