### ISSUE TITLE
Tool chain examples

### ISSUE THREAD

**Issue by jbeckton** [TypeStrong/tsconfig#18]
Got any examples on how this fits into a developers tool chain? I use Gulp specifically.

**Comment by blakeembrey** [comment]
Honestly, I don't know what you're asking for at all. What do you want to do?

**Comment by jbeckton** [comment]
Well, given your typical Typescript app you have Gulp or Grunt or some other task runner to kick off ts compilation. I was looking for examples of how you would use this given that scenario.

**Comment by blakeembrey** [comment]
> What do you want to do?

**Comment by blakeembrey** [comment]
The README in this module states how to use it, but I really need to know what you're trying to do. I'm pretty sure this is the wrong place to ask.

**Comment by jbeckton** [comment]
Maybe your project's purpose is not that clear to me. So i'll ask what does tsconfig do? I was thinking that it plays a role in compiling Typescript files into JavaScript. Is that not what it does or does it do so much more that you need more specifics?

**Comment by jbeckton** [comment]
The README defines the API, I do not see one example of tsconfig actually being used. I can gather that it loads, reads and parses a tsconfig.json file, into memory? Then?  At some point the ts compiler needs that in order to do it's function.  Why is this not the place to ask questions? Is this not one of the intended purposes of this Github tool? to ask for enhancements... to the documentation?

**Comment by blakeembrey** [comment]
@jbeckton Please read the README. It is clearly stated on what it does and even has links you can review. I fail to understand what is missing for you, as you still have not said what you're trying to do for me to be able to help you.

**Comment by blakeembrey** [comment]
> So i'll ask what does tsconfig do?

https://github.com/TypeStrong/tsconfig#tsconfig

> I was thinking that it plays a role in compiling Typescript files into JavaScript.

No, it does not. As it says in the README, it parses a `tsconfig.json` file with support for `filesGlob` (which is an array of strings). 

> I do not see one example of tsconfig actually being used.

See the answer to question 1, it's just reads and parses `tsconfig.json` - do what you want with that.

> At some point the ts compiler needs that in order to do it's function.

Is this your question? You wish to what, compile something with TypeScript? Build your own implementation with the TypeScript compiler? 

> Why is this not the place to ask questions?

I didn't say it's not, I said I suspect you're asking in the wrong place based on what you're asking. This module has _nothing_ to do with Gulp or Grunt or anything. It's a utility, you use it as defined in the README.

> Is this not one of the intended purposes of this Github tool? to ask for enhancements... to the documentation?

Yes, it is. But people offer to help you in their own time, it's not possible to help when you don't answer questions.

If you want to compile TypeScript using Gulp, look at something that does just that. I'd try `gulp-typescript`.
