### ISSUE TITLE
`include` / `exclude` expansion

### ISSUE THREAD

**Issue by basarat** [TypeStrong/tsconfig#19]
@blakeembrey are any of your projects doing this? I need it for almtools :) :rose:

**Comment by blakeembrey** [comment]
I'm not, I'm relying on `tsc` anyway 😄 If you're interested in adding it, a new method would work best - something that takes a config file and expands it with `files` according the spec?

**Comment by basarat** [comment]
> If you're interested in adding it

naa all good. Was just curious if I was missing something obvious :rose:

**Comment by blakeembrey** [comment]
Nope, sorry - this is largely a non-buggy version of `tsc`'s `tsconfig.json` file resolution right now. However, it might be worth adding if I can do some investigation into the step when `include` is being processed (do you know?). If it's before creating the program, it might be worth replicating and building the feature that ignores regular `.ts` files as they aren't relevant when compiling using `ts-node`, `ts-loader`, etc.

**Comment by basarat** [comment]
`parseConfigFileContents` seems to put it into `fileNames` as fully expanded normalized `c:/foo/bar.ts` etc names  : https://github.com/Microsoft/TypeScript/pull/8841/files#diff-057bf8560e435e388ba45f7810c3d08dL697

I'll link back for your reference once I've done the investigation :rose:

**Comment by basarat** [comment]
This always gives reliable `files` : 

```ts
    try {
        const tsResult = ts.parseJsonConfigFileContent(projectSpec, ts.sys, path.dirname(projectFile), null, projectFile);
        console.log(tsResult); // DEBUG
        projectSpec.files = tsResult.fileNames || [];
    }
    catch (ex) {
        return {
            error: makeBlandError(projectFilePath,ex.message)
        }
    }
```

Tested with 

* If nothing is specified
* If just `files` is specified
* If `include` or `exclude` is specified 

:) :heart: :rose:

**Comment by blakeembrey** [comment]
Nice! I think I already use that everywhere, might just be a matter of filtering that list down the `.d.ts` files for these projects 😄

**Comment by basarat** [comment]
PS the try catch is just me being cautious, I have no actual evidence of its need. I already had it in place for my old glob expander so left it in for myself. I wouldn't add it if its not already there :) :heart:
