### ISSUE TITLE
tsconfig.json become not readable

### ISSUE THREAD

**Issue by wilfrem** [TypeStrong/tsconfig#2]
reading tsconfig.json using this module, it's updated and become not readable.
Please, add optional argument(tab or space) to JSON.stringify or add no-update option when read.

**Comment by basarat** [comment]
There is a lot of work that has gone into `tsconfig.json` reading here : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts that needs to be pulled in here. 

The plan is to make atomts so great for TypeScript that splitting into seperate NPM modules is a near 0 time consuming task. Once that is done I'll upstream those changes here. Till then you can bring in that code base for yourself in your projects if you want. Thank you for your patience :heart:

**Comment by blakeembrey** [comment]
I was using this and certainly did not expect this to happen. Could you document that this happening in the readme, if you're going to keep it around?

**Comment by basarat** [comment]
@blakeembrey I've added you as a collab to the repo + owner of the npm package. So do whatever you want :rose:

**Comment by basarat** [comment]
@blakeembrey you can edit `package.json` to add your name as the owners as well

**Comment by blakeembrey** [comment]
Ok, thanks. I really only wanted to abstract the recursively lookup out of my code :stuck_out_tongue:

**Comment by basarat** [comment]
> wanted to abstract the recursively lookup out of my code

Use this : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/tsconfig/tsconfig.ts#L683-L710

**Comment by blakeembrey** [comment]
Hi @wilfrem! I've refactored the module and it has no side effects anymore. It should work for you now, please give it a go if you need to resolve or read `tsconfig.json` still :smile:

**Comment by wilfrem** [comment]
thx! :+1:
